fr-FR: Apply #2284 & #2286
OpenRCT2/Localisation pull request #2288
Opened 2022-03-14 06:23 UTC by ldanet

Applying for issue(s):
- #2284 
- #2286

2022-03-14 20:17 UTC, Gymnasiast commented
Tagging @rmnvgr to check. (You may converse in French if necessary.)

2022-03-15 08:48 UTC, rmnvgr requested changes

2022-03-15 08:48 UTC, rmnvgr commented on data/language/fr-FR.txt
> +STR_6467    :Nausée: {COMMA2DP32}
Espace insécable devant les deux points :

```suggestion
STR_6463    :Excitation : {COMMA2DP32}
STR_6464    :Intensité
STR_6465    :Intensité : {COMMA2DP32}
STR_6466    :Nausée
STR_6467    :Nausée : {COMMA2DP32}
```

2022-03-15 08:48 UTC, rmnvgr commented on data/language/fr-FR.txt
> +STR_6468    :Pas encore connu
La fenêtre d’informations de l’attraction utilise « Pas encore disponible », il vaudrait mieux utiliser les mêmes termes (et ça évite de se poser la question de savoir si l’on accorde « connu » au masculin ou au féminin) :

```suggestion
STR_6468    :Pas encore disponible
```

2022-03-15 09:18 UTC, ldanet commented on data/language/fr-FR.txt
> +STR_6468    :Pas encore connu
En anglais, la fenêtre d'information dit "Not yet available" mais ici c'était "Not yet known" d'où la différence. Mais bien vu pour l'accord, en l'occurence ç'aurait été `connue` pour excitation/nausée/intensité mais oui, `disponible` c'est plus sûr. Rien que pour ça ça me paraît une bonne idée de le changer.

2022-03-15 09:33 UTC, rmnvgr commented
@ldanet Merci !

@Gymnasiast Looks good to me!

2022-03-15 10:43 UTC, merged