fr-FR: Various improvements
OpenRCT2/Localisation pull request #2612
Opened 2023-04-08 04:27 UTC by hlabrand

Hello! I read the whole fr-FR.txt file from beginning to end and fixed a few problems, ranging from typos to missing translations and a few suggested improvements. I have tried to separate them in different commits so it's easier to review. Let me know if you have any questions! Thanks!

2023-04-08 19:36 UTC, tupaschoal commented
Wanna double check @rnmvgr?

2023-04-08 19:56 UTC, rmnvgr requested changes
@hlabrand Thanks a lot! I made a few suggestions to your changes.

2023-04-08 19:56 UTC, rmnvgr commented on data/language/fr-FR.txt
> +STR_6533    :{WINDOW_COLOUR_2}Indice d'engouement : {BLACK}-{COMMA16}%
```suggestion
STR_6533    :{WINDOW_COLOUR_2}Indice d’engouement : {BLACK}-{COMMA16}%
```

2023-04-08 19:56 UTC, rmnvgr commented on data/language/fr-FR.txt
> +STR_DTLS    :Le mont Vésuve a enseveli Pompéi et Herculanum en 79 av.J.C. Visitez le site de fouilles et construisez un parc !{NEWLINE}Par : Katatude
```suggestion
STR_DTLS    :Le mont Vésuve a enseveli Pompéi et Herculanum en 79 av. J.-C. Visitez le site de fouilles et construisez un parc !{NEWLINE}Par : Katatude
```

2023-04-08 21:08 UTC, hlabrand commented
Great suggestions, well spotted! Thank you!

2023-04-09 16:26 UTC, rmnvgr approved these changes
Looks good to me 👍

2023-04-09 17:07 UTC, merged