nl-NL: Apply #2678, #2679, #2692
OpenRCT2/Localisation pull request #2695
Opened 2023-12-20 13:37 UTC by karst

Applying for issue(s):
- #2678
- #2679
- #2692

2023-12-20 13:40 UTC, Gymnasiast commented
I’d like to review this one.

2023-12-20 13:41 UTC, karst commented
Hah I wanted to tag you, you were ahead of me :joy:

2023-12-20 14:38 UTC, tupaschoal approved these changes
Waiting on @Gymnasiast review

2023-12-22 11:39 UTC, Gymnasiast requested changes
Sorry for the delay, I had to check some existing strings.

2023-12-22 11:39 UTC, Gymnasiast commented on data/language/nl-NL.txt
> +STR_6593    :Verwijder park hekjes
```suggestion
STR_6593    :Parkafscheiding verwijderen
```
(Samenstellingen moeten aan elkaar en de andere wijzigingen zijn omwille van consistentie.)

2023-12-22 11:39 UTC, Gymnasiast commented on data/language/nl-NL.txt
> +STR_6594    :Vakinspecteur: Helling muur aan/uit
```suggestion
STR_6594    :Vakinspecteur: Helling muur instellen
```
Deze knop wisselt tussen 3 statussen: geen helling, ene punt omhoog, andere punt omhoog.

2023-12-22 12:34 UTC, Gymnasiast approved these changes

2023-12-22 12:36 UTC, merged